not nice commit msg

diff --git a/jenkins-x.yml b/jenkins-x.yml
--- a/jenkins-x.yml
+++ b/jenkins-x.yml
@@ -21,13 +21,13 @@ pipelineConfig:
         steps:
           - name: conventionalcommits-check
             image: aevea/commitsar:latest
-            command: $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' >> check.failed ; exit 0; }
+            command: $(commitsar > $CONV_COMMIT_FILE 2> commit.check.failed) || { echo 'commit check failed' >> $CONV_COMMIT_ERR_FILE; exit 0; }
           - name: conventionalcommits-print
-            command: cat commit.check
+            command: cat $CONV_COMMIT_FILE
           - name: conventionalcommits-comment
             command: |
-              if [ -f "check.failed" ]; then
-                  jx step pr comment -c "\`\`\`$(cat commit.check)\`\`\`"
+              if [ -f "$CONV_COMMIT_ERR_FILE" ]; then
+                  jx step pr comment -c "HASH | ERROR | MSG \n --|--|-- \n $(cat conv.txt| grep "|" | awk  -F"|" '{printf "%s | %s | %s", $2, $3, $4;} {print ""}' | grep -v -e '^[[:space:]]*$' | tail -n +2 | grep '[[:alnum:]]')"
                   exit 1;
               else
                  echo 'COMMIT MSG CHECK PASSED'
