chore(pipeline): add conventional commits

diff --git a/jenkins-x.yml b/jenkins-x.yml
--- a/jenkins-x.yml
+++ b/jenkins-x.yml
@@ -8,12 +8,12 @@ pipelineConfig:
         steps:
           - name: conventionalcommits-check
             image: aevea/commitsar:latest
-            command: $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' ; exit 0; }
+            command: $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' >> check.failed ; exit 0; }
           - name: conventionalcommits-print
             command: cat commit.check
           - name: conventionalcommits-comment
             command: |
-              if [ -f "commit.check.failed" ]; then
+              if [ -f "check.failed" ]; then
                   jx step pr comment -c "\`\`\`$(cat commit.check)\`\`\`"
                   exit 1;
               else
