chore(pipeline): add conventional commits

diff --git a/jenkins-x.yml b/jenkins-x.yml
--- a/jenkins-x.yml
+++ b/jenkins-x.yml
@@ -1,9 +1,24 @@
 buildPack: gradle
 pipelineConfig:
   agent:
-    image: gradle5-java11
+    image: gcr.io/jenkinsxio/builder-gradle5-java11:latest
   pipelines:
     pullRequest:
+      preBuild:
+        steps:
+          - name: conventionalcommits-check
+            image: aevea/commitsar:latest
+            command: $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' ; exit 0; }
+          - name: conventionalcommits-print
+            command: cat commit.check
+          - name: conventionalcommits-comment
+            command: |
+              if [ -f "commit.check.failed" ]; then
+                  jx step pr comment -c "\`\`\`$(cat commit.check)\`\`\`"
+                  exit 1;
+              else
+                 echo 'COMMIT CHECK PASSED!'
+              fi
       postBuild:
         steps:
           - name: sonar-check-dir
