chore: new pipelines

diff --git a/.lighthouse/jenkins-x/conventionalcommits.yaml b/.lighthouse/jenkins-x/conventionalcommits.yaml
--- a/.lighthouse/jenkins-x/conventionalcommits.yaml
+++ b/.lighthouse/jenkins-x/conventionalcommits.yaml
@@ -225,22 +225,22 @@ spec:
                   value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
               image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
               name: git-merge
-            - name: conventionalcommits-check
-              image: aevea/commitsar:latest
-              command:
-                - $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' >> check.failed ; exit 0; }
-            - name: conventionalcommits-print
-              command:
-                - cat commit.check
-            - name: conventionalcommits-comment
-              command:
-                - >
-                  if [ -f "check.failed" ]; then
-                  jx step pr comment -c "\`\`\`$(cat commit.check)\`\`\`"
-                  exit 1;
-                  else
-                     echo 'COMMIT MSG CHECK PASSED'
-                  fi
+#            - name: conventionalcommits-check
+#              image: aevea/commitsar:latest
+#              command:
+#                - $(commitsar > commit.check 2> commit.check.failed) || { echo 'commit check failed' >> check.failed ; exit 0; }
+#            - name: conventionalcommits-print
+#              command:
+#                - cat commit.check
+#            - name: conventionalcommits-comment
+#              command:
+#                - >
+#                  if [ -f "check.failed" ]; then
+#                  jx step pr comment -c "\`\`\`$(cat commit.check)\`\`\`"
+#                  exit 1;
+#                  else
+#                     echo 'COMMIT MSG CHECK PASSED'
+#                  fi
           volumes:
             - name: volume-0
               secret:
