chore: add snyk container test

diff --git a/.lighthouse/jenkins-x/pullrequest.yaml b/.lighthouse/jenkins-x/pullrequest.yaml
--- a/.lighthouse/jenkins-x/pullrequest.yaml
+++ b/.lighthouse/jenkins-x/pullrequest.yaml
@@ -303,8 +303,8 @@ spec:
                 source /workspace/source/.jx/variables.sh
                 export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
 
-                echo -e "About to run snyk ${YELLOW}monitor ${NOCOLOR}for image: ${GREEN}$OUTPUT_IMAGE${NOCOLOR}"
-                snyk container monitor --project-name=$PROJECT_NAME $OUTPUT_IMAGE
+                echo -e "About to run ${YELLOW}snyk monitor ${NOCOLOR}for image: ${GREEN}$OUTPUT_IMAGE${NOCOLOR}"
+                snyk container monitor -remote-repo-url=$PROJECT_NAME --project-name=$PULL_NUMBER $OUTPUT_IMAGE
               volumeMounts:
                 - name: docker-socket
                   mountPath: /var/run/docker.sock
@@ -315,16 +315,16 @@ spec:
                 source /workspace/source/.jx/variables.sh
                 export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
 
-                echo -e "About to run snyk ${YELLOW}test ${NOCOLOR}for image: ${GREEN}$OUTPUT_IMAGE${NOCOLOR}"
+                echo -e "About to run ${YELLOW}snyk test ${NOCOLOR}for image: ${GREEN}$OUTPUT_IMAGE${NOCOLOR}"
                 if snyk container test --project-name=$PROJECT_NAME --severity-threshold=$SEVERITY_THRESHOLD $OUTPUT_IMAGE; then
-                  jx step pr comment -c "$(echo -e ":x: [Snyk Container Test Failed](https://www.conventionalcommits.org) :cursing_face:)"
-                  exit 1;
-                else
                   echo "No issues found for ${GREEN}$OUTPUT_IMAGE with severity level ${YELLOW}$SEVERITY_THRESHOLD"
+                else
+                  jx step pr comment -c "$(echo -e ":x: [ Snyk Container Test Failed ](https://www.conventionalcommits.org) :cursing_face:)"
+                  exit 1;
                 end
               env:
                 - name: SEVERITY_THRESHOLD
-                  value: high
+                  value: medium
               volumeMounts:
                 - name: docker-socket
                   mountPath: /var/run/docker.sock
