chore: add snyk container test

diff --git a/.lighthouse/jenkins-x/pullrequest.yaml b/.lighthouse/jenkins-x/pullrequest.yaml
--- a/.lighthouse/jenkins-x/pullrequest.yaml
+++ b/.lighthouse/jenkins-x/pullrequest.yaml
@@ -318,6 +318,7 @@ spec:
                 echo -e "About to run ${YELLOW}snyk test ${NOCOLOR}for image: ${GREEN}$OUTPUT_IMAGE${NOCOLOR}"
                 if snyk container test --project-name=$PROJECT_NAME --severity-threshold=$SEVERITY_THRESHOLD $OUTPUT_IMAGE; then
                   echo "No issues found for ${GREEN}$OUTPUT_IMAGE with severity level ${YELLOW}$SEVERITY_THRESHOLD"
+                  echo "snyk fail" > snyk.failed
                 else
                   jx step pr comment -c "$(echo -e ":x: [ Snyk Container Test Failed ](https://www.conventionalcommits.org) :cursing_face:")"
                   exit 1;
@@ -328,6 +329,15 @@ spec:
               volumeMounts:
                 - name: docker-socket
                   mountPath: /var/run/docker.sock
+            - name: snyk-container-test
+              image: "snyk/snyk:docker"
+              script: |
+                source /workspace/source/.jx/variables.sh
+                export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
+                if [ -f snyk.failed ]; then
+                  jx step pr comment -c "$(echo -e ":x: [ Snyk Container Test Failed ](https://www.conventionalcommits.org) :cursing_face: \nImage: $OUTPUT_IMAGE")"
+                  exit 1;
+                fi
 
             - args:
                 - source /workspace/source/.jx/variables.sh && jx preview create
